site_name: Welcome to Lu Lab @ Tsinghua
theme:
  logo: img/Z-1.png
  name: material
 # palette:
 #   primary: custom
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.sections
    - navigation.expand
  markdown_extensions:
    - admonition
    - footnotes
    - attr_list
    - Highlight
extra_css: [extra.css] 
extra: 
  homepage: /home
markdown_extensions: 
  - tables
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - toc:
      toc_depth: 3 # This will include headings up to level 3 (h1, h2, h3)

plugins:
  - callouts
  - search
  - meta
  - glightbox:
     effect: zoom
  - mkdocs-audio
  - mkdocs-video:
     is_video: True
     video_loop: True
     video_muted: True
     video_controls: True
     video_autoplay: True
     css_style:
        max-height: 180px /* match with default img height in extra.css */
        margin-right: 15px
        vertical-align: left
        border: 2px solid grey
        border-radius: 8px
  - redirects:
      redirect_maps:
        'home/index.md': 'https://www.ncrnalab.org/home'
        'home/software/index.md': 'https://www.ncrnalab.org/home/software'
        'home/ai/index.md': 'https://www.ncrnalab.org/home/ai'
#  - encryptcontent:
#      password_inventory:
#        classified: setapassword
#        confidential: setanotherpasswordhere

repo_url: https://github.com/lulab
repo_name: github/lulab
nav:
  - Home: /home
  - Projects: 
    - 科研课题: projects/proj.md
    - Research Projects: projects/proj-en.md
    - Funding: projects/funding.md
  - Courses:
    - Courses: courses/index.md 
    - Bioinformatics: courses/bioinfo.md
    - AI for Biomedicine: courses/ai.md
    - Genomics - PTN: courses/genomics.md
  - Publications: 
    - By Year: publications/pub.md
    - By Topic: publications/pub-topics.md
    - <b>Tips for Writing</b>: publications/writing.md
    - Patent: publications/IP.md
    - News: publications/news.md
  - People: 
    - People: people/index.md
    - Academic Tree: people/academic.md
    - Join Us: people/join-us.md
    - Collaborations: people/open.md
  - Literature Reading:
    - Literature Reading: reading/index.md
    - <b>Startup Readings</b>: reading/startup.md
    - A.RNAfinder:
      - 1.1 cfRNAfinder: 
        - Overview: reading/A.RNAfinder/1.1 cfRNAfinder/index.md  
        - 1. cf-seq Tech: reading/A.RNAfinder/1.1 cfRNAfinder/1. cf-seq Tech.md
        - 2. cfRNA: reading/A.RNAfinder/1.1 cfRNAfinder/2. cfRNA.md
        - 3. cfRNA Analysis: reading/A.RNAfinder/1.1 cfRNAfinder/3. cfRNA Analysis.md
        - 4. cfDNA+: reading/A.RNAfinder/1.1 cfRNAfinder/4. cfDNA+.md
        - 5. Panel and Database: reading/A.RNAfinder/1.1 cfRNAfinder/5. Panel and Database.md
      - 1.2 ncRNAfinder: 
        - Overview: reading/A.RNAfinder/1.2 ncRNAfinder/index.md  
        - 1. dsRNAfinder: reading/A.RNAfinder/1.2 ncRNAfinder/1. dsRNAfinder.md
        - 2. mbRNAfinder: reading/A.RNAfinder/1.2 ncRNAfinder/2. mbRNAfinder.md 
      - 2.1 Precision Medicine:
        - 1. Immune RNA: reading/A.RNAfinder/2.1 Precision Medicine/1. Immune RNA.md
        - 2. Cancer RNA: reading/A.RNAfinder/2.1 Precision Medicine/2. Cancer RNA.md
        - 3. Immune Diseases: reading/A.RNAfinder/2.1 Precision Medicine/3. Immune Diseases.md
        - 4. Cancer Immunotherapy: reading/A.RNAfinder/2.1 Precision Medicine/4. Cancer Immunotherapy.md
        - Analysis - Genetics & Function: reading/A.RNAfinder/2.1 Precision Medicine/Analysis - Genetics & Function.md
        - Analysis - RNA Regulation: reading/A.RNAfinder/2.1 Precision Medicine/Analysis - RNA Regulation.md
        - Analysis - Single Cell: reading/A.RNAfinder/2.1 Precision Medicine/Analysis - Single Cell.md
        - Multi-modal Model: reading/A.RNAfinder/2.1 Precision Medicine/Multi-modal Model.md
        - Multiomics Analysis: reading/A.RNAfinder/2.1 Precision Medicine/Multiomics Analysis.md
      - 2.2 Structure Design: 
        - 2nd Structure Prediction: reading/A.RNAfinder/2.2 Structure/2nd Structure Prediction.md
        - 3D Structure Prediction: reading/A.RNAfinder/2.2 Structure/3D Structure Prediction.md
        - RNA & Protein Design: reading/A.RNAfinder/2.2 Structure/RNA & Protein Design.md
    - B.RNAtalk: 
      - RNA-RNA:
        - Overview: reading/B.RNAtalk/RNA-RNA/index.md
        - Analysis - Regulome: reading/B.RNAtalk/RNA-RNA/Analysis - Regulome.md
        - Seq - Interaction: reading/B.RNAtalk/RNA-RNA/Seq - Interaction.md
        - Seq - Single Cell: reading/B.RNAtalk/RNA-RNA/Seq - Single Cell.md
        - siRNA Drug Design: reading/B.RNAtalk/RNA-RNA/siRNA Drug Design.md
      - RNA-Ligand: reading/B.RNAtalk/RNA-Ligand//RNA-Ligand.md
      - RNA-Protein: reading/B.RNAtalk/RNA-Protein/RNA-Protein.md
  - Intranet Docs: 
    - Getting Started: index.md
    - Intranet: intranet/index.md
    - Lab Meetings: intranet/meeting.md
    - Lab Calendars: intranet/cal.md
    - FAQ: 
      - I.科研方法: faq/faq-1.md
      - II.科研实践: faq/faq-2.md
      - III.实验室规范: faq/faq-3.md
      - IV.生活和财务: faq/faq-4.md
      - V.办公硬件和软件: faq/faq-5.md
      - VI.其他问题: faq/faq-6.md
    - Programming: 
      - Linux:
        - 1.VS Code Remote: program/vscode.md    
        - 2.Conda in Linux: program/conda.md    
        - 3.Tips in Linux: program/tips.md
      - MacOS:
        - 1.Mac Settings: program/macos.md
        - 2.Homebrew & Pip: program/homebrew.md
        - 3.MkDocs & Jekyll: program/mkdocs-jekyll.md  

