site_name: Lu Lab Docs
#site_url: https://lulab.github.io/mkdocs
site_url: http://lulab.life.tsinghua.edu.cn/docs
theme:
  logo: img/Z-1.png
  name: material
 # palette:
 #   primary: custom
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.sections
  markdown_extensions:
    - admonition
    - footnotes
    - attr_list
    - Highlight
extra_css: [extra.css] 
extra: 
  homepage: http://lulab.life.tsinghua.edu.cn
markdown_extensions: 
  - tables
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight


plugins:
  - callouts
  - search
  - meta
  - glightbox:
     effect: zoom
  - mkdocs-audio
  - mkdocs-video:
     is_video: True
     video_loop: True
     video_muted: True
     video_controls: True
     video_autoplay: True
     css_style:
        max-height: 180px /* match with default img height in extra.css */
        margin-right: 15px
        vertical-align: left
        border: 2px solid grey
        border-radius: 8px
#  - encryptcontent:
#      password_inventory:
#        classified: setapassword
#        confidential: setanotherpasswordhere

repo_url: https://github.com/lulab
repo_name: github/lulab
nav:
  - Home: http://lulab.life.tsinghua.edu.cn
  - Getting Started: 
    - Getting Started: index.md
    - 1.Lab Meetings: meeting/meeting.md
    - 2.Lab Calendar: meeting/cal.md
    - FAQ: 
      - I.科研方法: faq/faq-1.md
      - II.科研实践: faq/faq-2.md
      - III.实验室规范: faq/faq-3.md
      - IV.生活和财务: faq/faq-4.md
      - V.办公硬件和软件: faq/faq-5.md
      - VI.其他问题: faq/faq-6.md
    - Intranet: 
      - 1.Network: intranet/network.md
      - 2.Facilities & Instructions: intranet/facilities.md
    - Programming: 
      - 1.Mac Settings: program/macos.md
      - 2.Homebrew & Pip: program/homebrew.md
      - 3.MkDocs & Jekyll: program/mkdocs-jekyll.md      
  - Literature Reading:
    - Tips for paper reading: reading/reading.md
    - Seq. Tech.:
      - Interaction-seq: reading/seq-tech/interaction-seq.md
      - Single-Cell-seq: reading/seq-tech/single-cell-seq-tech.md
      - cfRNA/DNA-seq: reading/seq-tech/cfrna-seq-tech.md
    - Omics Data Analysis:
      - Transcriptomics: 
        - cfRNA Analysis: reading/omics/rna/cfrna.md
        - Regulome Analysis: reading/omics/rna/regulome.md
        - POSTAR Analysis: reading/omics/rna/postar.md
      - MultiOmics:
        - MultiOmics Data Analysis: reading/omics/multiomics/multiomics.md
        - Single Cell Data Analysis: reading/omics/multiomics/single-cell-data-analysis.md
        - Genetic & Function Analysis: reading/omics/multiomics/genetic-and-function-analysis.md
      - Microbiome: reading/omics/microbiome.md
    - Precision Medicine: 
      - Cancer: 
        - ncRNA in Cancer: reading/med/cancer/ncrna.md
        - Cancer Immunotherapy: reading/med/cancer/cancer-immunotherapy.md
      - Immunity: 
        - RNA in Immune System: reading/med/immunity/RNA-immune.md
        - Immune Diseases: reading/med/immunity/immune-diseases.md
      - Liquid Biopsy:  
        - Overview: reading/med/liquid-biopsy/index.md       
        - cfRNA: reading/med/liquid-biopsy/cfRNA.md
        - cfDNA +: reading/med/liquid-biopsy/cfDNA.md
        - Panel and Database: reading/med/liquid-biopsy/panel-and-screen.md
    - Artificial Intelligence:
      - Overview: reading/ai/index.md 
      - Multi-modal: reading/ai/multi-modal.md
      - RNA Modeling - SEQ: 
        - RNA 2nd Structure Prediction: reading/ai/rna-modeling-seq/rna-2nd-structure.md
        - RNA Motif & dsRNAfinder: reading/ai/rna-modeling-seq/rna-motif-and-dsrnafinder.md
        - RNA-RNA Interaction: reading/ai/rna-modeling-seq/rna-rna-interaction.md
        - RNA-Oligo: reading/ai/rna-modeling-seq/rna-oligo.md
      - RNA Modeling - STRUCTURE: 
        - RNA 3D Structure Prediction: reading/ai/rna-modeling-structure/rna-3d-structure-prediction.md
        - RNA-Ligand: reading/ai/rna-modeling-structure/rna-ligand.md
        - RNA-Protein: reading/ai/rna-modeling-structure/rna-protein.md
        - RNA & Protein Design: reading/ai/rna-modeling-structure/rna-and-protein-design.md
  - Publications: 
    - By Year: pub/pub.md
    - By Topic: pub/pub-topics.md
    - Software: pub/software.md
    - Tips for Writing: pub/writing.md
  - Projects:
    - Background: proj/background.md
    - Research Projects: proj/proj.md
    - Funding: proj/funding.md
  - Courses:
    - Courses: courses/index.md 
    - Bioinformatics: courses/bioinfo.md
    - AI for Biomedicine: courses/ai.md
    - Genomics - PTN: courses/genomics.md
